name: Publish Docker image to GitHub Container Registry (multi-arch)

on:
  schedule:
    # Jeden Sonntag um Mitternacht
    - cron: '0 0 * * 0'
  workflow_dispatch: {} # Optional: manueller Start möglich

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [14.2.0, 14.1.0]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/minegamer95/docker-mediathekview-webinterface

      - name: Build and push Docker image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          build-args: |
            MEDIATHEK_VERSION=${{ matrix.version }}
          tags: |
            ghcr.io/minegamer95/docker-mediathekview-webinterface:${{ matrix.version }}
            ${{ matrix.version == '14.2.0' && 'ghcr.io/minegamer95/docker-mediathekview-webinterface:latest' || '' }}
          labels: |
            org.opencontainers.image.version=${{ matrix.version }}
